### ISSUE TITLE
BinaryFileManager when the width is applied image is created with gray border

### ISSUE THREAD

**Issue by kpmrafeeq** [dd4t/DD4T.MVC#25] opened 2017-03-27 12:00 UTC
This is visible when we have some white area in the image, open below image in IE then you can understand better, because in Chrom we have default black area and it cannot be visible.

![test image](https://cloud.githubusercontent.com/assets/1480591/24355284/5b050502-1306-11e7-8776-25ae0f387c56.png)

**Comment by ThijsBorst** [comment] 2017-03-27 12:17
In which version of DD4T does this occur?

**Comment by kpmrafeeq** [comment] 2017-03-27 17:06
It is also there in 2.1.0

**Comment by ThijsBorst** [comment] 2017-03-30 08:36
I can reproduce this issue. Fix is coming.

**Comment by ThijsBorst** [comment] 2017-03-30 13:15
The issue is fixed. I've submitted two pull requests. Waiting for review...

**Comment by ThijsBorst** [comment] 2017-03-30 18:11
Fixed in Core Release 2.2.3, which is available now.

**Closed by ThijsBorst** 2017-03-30 18:11 UTC
Labels: bug

**Comment by kpmrafeeq** [comment] 2017-03-31 10:31
Thank you
